Repository FromDoppler/unlayer-editor, pull requests merged in 2021-08, with the labels that each got.

#2 [DE-243] Automatizar validación de Prettier
  .eslintrc.json
  .prettierrc.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: size/L

#1 DE-248 Jenkins configuration and publish cdn
  .dockerignore
  .doppler-ci
  .gitattributes
  .gitlint
  Dockerfile
  Jenkinsfile
  build-n-publish.sh
  gitlint.sh
  package-lock.json
  public/index.html
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
Labels: size/L

#4 chore: define .ico files as binary
  .gitattributes
Labels: size/XS

#3 [DE-245] Agregar editorConfig
  .dockerignore
  .editorconfig
  package.json
  public/favicon.ico
  yarn.lock
Labels: size/M

#5 DE-252 - Generate semantic version numbers
  Jenkinsfile
  build-n-publish.sh
Labels: size/L

#6 DE-262 Definition of base URL and .env files
  .env.production
Labels: size/XS

#7 DE-258- Upload semantic version friendly manifests to CDN
  Dockerfile
  build-n-publish.sh
  cdn-helpers/prepare.sh
  cdn-helpers/upload.sh
Labels: size/L

#8 DE-263 - CI/CD documentation
  .prettierignore
  .vscode/settings.json
  README.md
  docs/pr-generated-files.png
  package.json
Labels: size/L

#9 chore: configure dependabot
  .github/dependabot.yml
Labels: size/S

#18 Synchronize node and @types/node dependencies
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: size/XS

#24 Accept npm v14.x versions only
  .github/dependabot.yml
Labels: size/XS

#29 chore(deps): configure dependabot to keep using node 14
  .github/dependabot.yml
Labels: size/XS

#31 DE-253 Add basic configuration for test coverage greater than 80%
  Dockerfile
  README.md
  package.json
  src/App.tsx
  src/index.test.tsx
Labels: size/M

#25 DE-242 Basic config to multiple custom tools
  README.md
  public/socialTool.js
  public/subscribeTool.js
  src/App.tsx
Labels: size/L

#36 DE-269 - Format validation fix
  .editorconfig
  .prettierignore
Labels: size/XS

#37 Remover archivos no usados
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/logo.svg
Labels: size/M

#42 DE-265 Config files uploads to S3
  README.md
  docs/aws-uncheck-s3-block-all-public-access.png
  docs/config-unlayer-init-project-id.png
  docs/config-unlayer-settings-storage-aws-s3.png
  docs/test-s3-upload-same-image.png
  docs/test-unlayer-aws-s3-success-full-configuration.png
  docs/test-unlayer-upload-same-image.png
Labels: size/L

#39 feat(editor): add social share custom tool with size property
  public/socialShare.js
  src/App.tsx
Labels: size/M

#47 [DE-274] Prepara ambiente de desarrollo para proyecto Unlayer
  .gitignore
  config-overrides-dev.js
  config-overrides-prod.js
  config-overrides.js
  package.json
  src/App.tsx
  webpack.config-dev.js
  yarn.lock
Labels: size/M

#56 DE-280 Config user signature in react-email-editor
  .env.development
  src/App.tsx
Labels: size/S
