Repository FromDoppler/unlayer-editor, pull requests merged in 2021-09, with the labels that each got.

#59 DE-287 add .env.development to git ignore
  .env.development
Labels: size/XS

#60 De 266 unlayer react component
  .editorconfig
  README.md
  config/env.js
  config/getHttpsConfig.js
  config/jest/babelTransform.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  package.json
  public/index.html
  scripts/build.js
  scripts/start.js
  scripts/test.js
  src/App.tsx
  src/customJs/index.js
  src/customJs/socialTool.js
  src/customJs/socialTool/FacebookProperty.js
  src/customJs/socialTool/LinkedInProperty.js
  src/customJs/socialTool/SocialTool.js
  src/customJs/socialTool/TwitterProperty.js
  src/index.css
  src/react-app-env.d.ts
  webpack.config-dev.js
  yarn.lock
Labels: size/XXL

#74 chore: remove package-lock.json
  package-lock.json
Labels: size/XS

#68 DE-271 update eslint configuration
  .eslintrc.json
  config-overrides.js
  src/App.tsx
  src/customJs/socialShareTool.js
  src/customJs/subscribeTool.js
  webpack.config-dev.js
Labels: size/M

#89 fix(deps): revert updates of postcss-flexbugs-fixes and webpack-dev-server
  package.json
  yarn.lock
Labels: size/XS

#90 fix(editor): update project id full paid account
  .env.development
Labels: size/XS

#94 DE-294 Add merge tags for use as custom fields
  src/App.tsx
  src/external/merge.tags.js
Labels: size/M

#106 Add social share tool
  src/App.tsx
  src/customJs/index.js
  src/customJs/socialShareTool.js
  src/customJs/socialShareTool/SocialShareTool.js
  src/customJs/socialShareTool/index.js
Labels: size/L

#109 [DE-298] Recibir un parámetro arbitrario en el init y renderizarlo en una custom tool
  src/App.tsx
  src/customJs/companyTitleDemo/CompanyTitle.js
  src/customJs/companyTitleDemo/index.js
  src/customJs/index.js
  src/customJs/sharedSingletonModule.js
Labels: size/M
