Repository FromDoppler/unlayer-editor, pull requests merged in 2022-04, with the labels that each got.

#306 Update dependencies
  package.json
  yarn.lock
Labels: size/M

#309 Use the same fix-format command convention used in other FE projects
  package.json
Labels: size/XS

#310 chore: minor changes in test configuration
  src/App.tsx
Labels: size/S

#311 [DE-564] Intl custom tool
  package.json
  src/App.tsx
  src/customJs/companyTitleDemo/index.js
  src/customJs/index.js
  src/customJs/localization.js
  src/customJs/localization.test.js
  src/customJs/socialShareTool/index.js
  src/customJs/socialShareTool/index.test.js
  src/customJs/socialTool/FacebookProperty.js
  src/customJs/socialTool/LinkedInProperty.js
  src/customJs/socialTool/SocialTool.js
  src/customJs/socialTool/TwitterProperty.js
  src/i18n/en.js
  src/i18n/es.js
  src/i18n/language-tests.test.js
  yarn.lock
Labels: size/L

#312 DE-562 - Customize Unlayer's default translated messages
  src/customJs/localization.js
  src/customJs/localization.test.js
  src/customJs/socialShareTool/index.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/S

#313 DE-570 - Micro-frontend Initialization
  src/App.tsx
  src/customJs/index.js
Labels: size/M
