Repository FromDoppler/unlayer-editor, pull requests merged in 2022-11, with the labels that each got.

#553 Update react v16 to v18
  package.json
  src/index.tsx
  yarn.lock
Labels: size/S

#564 chore: show explicit error when root element does not found
  src/index.tsx
Labels: size/S

#573 [DE-876] translate payu title button
  src/customJs/payuButtonTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#572 feat: add link property to payU button tool
  src/customJs/index.js
  src/customJs/linkProperty.js
  src/customJs/payuButtonTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#574 [DE-879] Rename PayU tool properties section
  src/customJs/payuButtonTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#576 Update dependencies
  package.json
  yarn.lock
Labels: size/S

#577 [DE-877] Help text for button payU properties
  src/customJs/linkProperty.js
  src/customJs/payuButtonTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#578 [DE-875] Update PayU button icon
  public/assets/Payu_Button.svg
  src/customJs/payuButtonTool/index.js
Labels: size/XS

#584 [DE-892] Add translation for social share title
  src/customJs/socialShareTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XS

#586 [DE-880] Validation for payu button
  public/assets/payu_button.svg
  src/customJs/payuButtonTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#587 [DE-895] Update icon button tool
  public/assets/button.svg
  src/App.tsx
Labels: size/S

#590 build: fix gitlint
  gitlint.sh
Labels: size/XS
