Repository FromDoppler/unlayer-editor, pull requests merged in 2022-02, with the labels that each got.

#264 DE-453 Typo in webpack config
  webpack.config.js
Labels: size/XS

#265 Add the property canonicalVersion to generated asset-manifest.json
  cdn-helpers/prepare.sh
Labels: size/S

#266 DE-453 Update hrefs with internal custom fields
  src/customJs/socialShareTool/SocialShareTool.js
Labels: size/M

#269 fix: update manifest structure
  webpack.config.js
Labels: size/XS
