Repository FromDoppler/unlayer-editor, pull requests merged in 2023-11, with the labels that each got.

#1095 feat: register product tool definition
  src/customJs/index.ts
Labels: size/XS

#1096 DOP-1485 - resolve visual issue on product tool
  src/customJs/tools/product/ProductViewer.test.jsx
  src/customJs/tools/product/ProductViewer.tsx
Labels: size/M

#1101 DOP-1485 - Add product tool transform
  src/customJs/tools/product/index.test.js
  src/customJs/tools/product/index.ts
  src/editorsWebappListenersRegistrator.ts
Labels: size/L
