Repository FromDoppler/unlayer-editor, pull requests merged in 2023-03, with the labels that each got.

#702 Ensure compatibility with image generation
  src/customJs/index.js
  src/customJs/localization.js
Labels: size/S

#706 DE-964 - All the literals
  src/customJs/localization.test.js
  src/customJs/payuButtonTool/PayuButtonTool.js
  src/customJs/payuButtonTool/index.js
  src/customJs/socialShareTool/configuration.js
  src/customJs/socialShareTool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XXL

#703 DE-964 - Spanish literals
  src/i18n/es.js
Labels: size/S

#709 Improvement the use of Unlayer's Type
  src/App.tsx
Labels: size/S

#708 [DE-963] Build custom css for Unlayer editor
  package.json
  src/App.tsx
  src/customJs/index.js
  src/customJs/main.css
  webpack.config.js
  yarn.lock
Labels: size/S

#715 Adjust tool's name when is too long
  src/customJs/main.css
Labels: size/XS

#721 Fix test
  src/customJs/commonProperties/linkProperty.test.js
Labels: size/XS
