Repository FromDoppler/unlayer-editor, pull requests merged in 2023-08, with the labels that each got.

#930 DOP-1416 - empty viewer
  src/customJs/components/EmptyViewer.test.js
  src/customJs/components/EmptyViewer.tsx
  src/customJs/tools/social_share_tool/SocialShareViewer.test.js
  src/customJs/tools/social_share_tool/SocialShareViewer.tsx
  src/customJs/tools/social_share_tool/index.ts
Labels: size/L

#932 chore: rename shop names based on MSEditor's constants
  src/App.tsx
  src/customJs/tools/promo_code/index.test.ts
Labels: size/M

#927 DOP-1417 - Obtain promotion codes
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/utils/dopplerAppBridge.test.ts
  src/customJs/utils/dopplerAppBridge.ts
Labels: size/L

#935 Dop 1417 treat reponse with promo code items
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/properties/promo_codes/types.ts
Labels: size/S

#940 chore: render harcoded promo codes for local env
  src/editorsWebappListenersRegistrator.ts
  src/index.tsx
Labels: size/M

#948 DOP-1421 - set promo code view
  src/customJs/tools/promo_code/PromoCodeValues.ts
  src/customJs/tools/promo_code/PromoCodeViewer.test.js
  src/customJs/tools/promo_code/PromoCodeViewer.tsx
Labels: size/M

#950 Reusable property helpers
  src/customJs/configuration.ts
  src/customJs/properties/helpers.test.ts
  src/customJs/properties/helpers.ts
  src/customJs/properties/promo_codes/index.ts
  src/customJs/tools/promo_code/index.ts
  src/customJs/types.ts
Labels: size/L

#953 DOP-1420 Set promo code property
  src/customJs/tools/promo_code/index.test.ts
  src/customJs/tools/promo_code/index.ts
Labels: size/M

#957 Dependant types
  src/customJs/properties/helpers.ts
  src/customJs/properties/promo_codes/index.ts
  src/customJs/tools/payu_button_tool/PayuButtonValues.ts
  src/customJs/tools/payu_button_tool/PayuButtonViewer.tsx
  src/customJs/tools/payu_button_tool/index.ts
  src/customJs/tools/payu_button_tool/types.ts
  src/customJs/tools/promo_code/PromoCodeValues.ts
  src/customJs/tools/promo_code/PromoCodeViewer.tsx
  src/customJs/tools/promo_code/index.test.ts
  src/customJs/tools/promo_code/index.ts
  src/customJs/tools/promo_code/types.ts
  src/customJs/tools/social_share_tool/SocialShareValues.ts
  src/customJs/tools/social_share_tool/SocialShareViewer.tsx
  src/customJs/tools/social_share_tool/index.ts
  src/customJs/tools/social_share_tool/types.ts
  src/customJs/types.ts
  src/customJs/utils/unlayer.tsx
Labels: size/L

#959 DOP-1419 - Add radio button as promo code selector
  src/customJs/properties/promo_codes/PromoCodesWidget.test.js
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
Labels: size/L

#963 More helpers
  src/customJs/properties/helpers.test.ts
  src/customJs/properties/helpers.ts
  src/customJs/properties/url/index.ts
  src/customJs/tools/payu_button_tool/index.ts
  src/customJs/tools/social_share_tool/index.ts
Labels: size/L

#962 DOP-1438 - No promocode available message
  src/customJs/properties/promo_codes/PromoCodesWidget.test.js
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/tools/promo_code/index.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/M

#964 Translation helper
  src/customJs/localization.test.js
  src/customJs/localization.ts
  src/customJs/properties/helpers.ts
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/properties/promo_codes/index.ts
  src/customJs/properties/url/UrlWidget.tsx
  src/customJs/tools/payu_button_tool/PayuButtonHelp.tsx
  src/customJs/tools/payu_button_tool/PayuButtonViewer.tsx
  src/customJs/tools/payu_button_tool/index.ts
  src/customJs/tools/promo_code/index.ts
  src/customJs/tools/social_share_tool/SocialShareViewer.tsx
  src/customJs/tools/social_share_tool/index.ts
Labels: size/L

#965 DOP-1439 - Register promocode tool without preview mode
  src/customJs/index.ts
Labels: size/XS

#967 DOP-1396 - Promo code style fix
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/tools/promo_code/index.ts
Labels: size/XS

#974 Update text content based on the last changes in the official repository
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/M

#966 DOP-1450 - Products gallery tool properties
  src/customJs/index.ts
  src/customJs/properties/helpers.ts
  src/customJs/tools/product/ProductViewer.tsx
  src/customJs/tools/product/index.ts
  src/customJs/tools/product/types.ts
  src/customJs/types.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/XL

#975 Parse external URLs configuration
  src/App.tsx
  src/customJs/configuration.test.js
  src/customJs/configuration.ts
Labels: size/M

#978 DOP-1452 - Product gallery button
  src/customJs/index.ts
  src/customJs/localization.ts
  src/customJs/properties/product_gallery/ProductGalleryValue.ts
  src/customJs/properties/product_gallery/ProductGalleryWidget.test.js
  src/customJs/properties/product_gallery/ProductGalleryWidget.tsx
  src/customJs/properties/product_gallery/index.ts
  src/customJs/tools/product/index.ts
  src/customJs/tools/product/types.ts
  src/customJs/types.ts
  src/customJs/utils/unlayer.tsx
  src/editorsWebappListenersRegistrator.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/L
