Repository FromDoppler/unlayer-editor, pull requests merged in 2023-07, with the labels that each got.

#879 DOP-1396 - Read stores configuration
  src/customJs/configuration.js
  src/customJs/configuration.test.js
  src/customJs/index.js
  src/customJs/socialShareTool/configuration.js
Labels: size/L

#884 Big code refactoring
  .editorconfig
  .prettierignore
  src/customJs/commonProperties/linkProperty.js
  src/customJs/components/PayuButtonViewer.js
  src/customJs/components/PayuButtonViewer.test.jsx
  src/customJs/components/SocialNetworksWidget.js
  src/customJs/components/SocialNetworksWidget.test.js
  src/customJs/components/SocialShareViewer.js
  src/customJs/components/Toggle.js
  src/customJs/components/UnlayerLabel.js
  src/customJs/components/UnlayerLabel.test.js
  src/customJs/components/UrlWidget.js
  src/customJs/components/UrlWidget.test.js
  src/customJs/constants.js
  src/customJs/index.js
  src/customJs/socialShareTool/SocialShareTool.js
  src/customJs/socialShareTool/configuration.js
  src/customJs/tools/getPayuButtonToolDefinition.js
  src/customJs/tools/getSocialShareToolDefinition.js
  src/customJs/tools/getSocialShareToolDefinition.test.js
  src/customJs/utils/unlayer.js
  src/customJs/utils/url.js
  src/customJs/utils/url.test.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/XL

#886 Remove redundant configuration
  src/App.tsx
  src/customJs/components/SocialNetworksWidget.test.js
  src/customJs/configuration.js
  src/customJs/configuration.test.js
  src/customJs/tools/getSocialShareToolDefinition.test.js
Labels: size/S

#888 Group properties and tools in folders
  src/customJs/index.js
  src/customJs/properties/social_networks/SocialNetworksWidget.js
  src/customJs/properties/social_networks/SocialNetworksWidget.test.js
  src/customJs/properties/social_networks/index.js
  src/customJs/properties/url/UrlWidget.js
  src/customJs/properties/url/UrlWidget.test.js
  src/customJs/properties/url/index.js
  src/customJs/tools/payu_button_tool/PayuButtonViewer.js
  src/customJs/tools/payu_button_tool/PayuButtonViewer.test.jsx
  src/customJs/tools/payu_button_tool/index.js
  src/customJs/tools/social_share_tool/SocialShareViewer.js
  src/customJs/tools/social_share_tool/index.js
  src/customJs/tools/social_share_tool/index.test.js
Labels: size/M

#889 Remove non-published images
  public/assets/button.svg
  public/assets/payu_button.svg
  src/App.tsx
  src/customJs/constants.js
  src/customJs/tools/payu_button_tool/index.js
  src/i18n/en.js
  src/i18n/es.js
Labels: size/M

#890 Update readme content
  README.md
Labels: size/XS

#899 Add types
  .babelrc
  .eslintrc.json
  package.json
  src/customJs/components/Toggle.tsx
  src/customJs/components/UnlayerLabel.test.js
  src/customJs/components/UnlayerLabel.tsx
  src/customJs/configuration.ts
  src/customJs/constants.ts
  src/customJs/index.ts
  src/customJs/localization.js
  src/customJs/localization.ts
  src/customJs/properties/social_networks/SocialNetworksValue.ts
  src/customJs/properties/social_networks/SocialNetworksWidget.js
  src/customJs/properties/social_networks/SocialNetworksWidget.test.js
  src/customJs/properties/social_networks/SocialNetworksWidget.tsx
  src/customJs/properties/social_networks/index.js
  src/customJs/properties/social_networks/index.ts
  src/customJs/properties/url/UrlValue.ts
  src/customJs/properties/url/UrlWidget.test.js
  src/customJs/properties/url/UrlWidget.tsx
  src/customJs/properties/url/index.js
  src/customJs/properties/url/index.ts
  src/customJs/tools/payu_button_tool/PayuButtonHelp.tsx
  src/customJs/tools/payu_button_tool/PayuButtonValues.ts
  src/customJs/tools/payu_button_tool/PayuButtonViewer.js
  src/customJs/tools/payu_button_tool/PayuButtonViewer.test.jsx
  src/customJs/tools/payu_button_tool/PayuButtonViewer.tsx
  src/customJs/tools/payu_button_tool/index.js
  src/customJs/tools/payu_button_tool/index.ts
  src/customJs/tools/social_share_tool/SocialShareValues.ts
  src/customJs/tools/social_share_tool/SocialShareViewer.tsx
  src/customJs/tools/social_share_tool/index.js
  src/customJs/tools/social_share_tool/index.ts
  src/customJs/types.ts
  src/customJs/unlayer-react.ts
  src/customJs/utils/unlayer.tsx
  src/customJs/utils/url.test.js
  src/customJs/utils/url.ts
  src/i18n/en.ts
  src/i18n/es.ts
  webpack.config.js
  yarn.lock
Labels: size/XL

#907 Preview mode configuration
  src/App.tsx
  src/customJs/configuration.test.js
  src/customJs/configuration.ts
  src/customJs/index.ts
  src/customJs/utils/unlayer.tsx
Labels: size/S

#904 Better types
  src/customJs/properties/social_networks/SocialNetworksWidget.tsx
  src/customJs/properties/social_networks/index.ts
  src/customJs/properties/url/UrlWidget.tsx
  src/customJs/properties/url/index.ts
  src/customJs/types.ts
  src/customJs/utils/unlayer.tsx
Labels: size/L

#905 Do not register the tool when the definition is undefined
  src/customJs/index.ts
  src/customJs/utils/unlayer.tsx
Labels: size/S

#908 Add HOC for adding labels to the widgets
  src/customJs/components/UnlayerLabel.tsx
  src/customJs/properties/social_networks/SocialNetworksWidget.tsx
  src/customJs/properties/social_networks/index.ts
  src/customJs/properties/url/UrlWidget.test.js
  src/customJs/properties/url/UrlWidget.tsx
  src/customJs/properties/url/index.ts
  src/customJs/tools/payu_button_tool/index.ts
  src/customJs/tools/social_share_tool/index.ts
  src/customJs/types.ts
  src/customJs/utils/unlayer.tsx
Labels: size/L

#911 fix: use the right property editor in social share tool
  src/customJs/tools/social_share_tool/index.ts
Labels: size/XS

#909 DOP-1396 - Promo codes tool preview version
  .eslintrc.json
  src/App.tsx
  src/customJs/configuration.ts
  src/customJs/constants.ts
  src/customJs/index.ts
  src/customJs/properties/promo_codes/PromoCodesWidget.tsx
  src/customJs/properties/promo_codes/index.ts
  src/customJs/properties/promo_codes/types.ts
  src/customJs/tools/promo_code/PromoCodeValues.ts
  src/customJs/tools/promo_code/PromoCodeViewer.tsx
  src/customJs/tools/promo_code/index.test.ts
  src/customJs/tools/promo_code/index.ts
  src/customJs/utils/promises.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/L
