Repository FromDoppler/unlayer-editor, pull requests merged in 2025-04, with the labels that each got.

#1552 DOP-1795 - Add logic for remove segment
  src/customJs/properties/wheel_list/wheelListWidget.tsx
Labels: size/XS

#1553 DOP-1796 - Add copy message
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/M

#1556 DOP-1791 - roulette fix issue
  src/customJs/properties/button_group/ButtonGroupWidget.tsx
  src/customJs/properties/wheel_list/wheelListWidget.tsx
  src/customJs/tools/wheel/index.ts
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/L

#1557 Permitir multi type
  src/App.tsx
  src/customJs/configuration.test.js
  src/customJs/configuration.ts
  src/customJs/constants.ts
  src/customJs/index.ts
  src/customJs/properties/product_gallery/ProductGalleryValue.ts
  src/customJs/tools/product/ProductViewer.tsx
  src/customJs/tools/product/index.ts
  src/customJs/tools/product/layout/layoutPosition01.tsx
  src/customJs/tools/product/types.ts
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
  src/editorsWebappListenersRegistrator.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/L

#1560 DOP-1791 - Roulette modal fix
  src/customJs/properties/wheel_list/index.ts
  src/customJs/properties/wheel_list/wheelListWidget.tsx
  src/customJs/tools/wheel/index.ts
  src/customJs/tools/wheel/types.ts
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
Labels: size/L

#1561 DOP-1791 - improve visual spaces
  src/customJs/properties/wheel_list/wheelListWidget.tsx
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
Labels: size/XS

#1558 Agregar info values en todos los layout position
  src/customJs/tools/product/layout/layoutPosition02.tsx
  src/customJs/tools/product/layout/layoutPosition03.tsx
  src/customJs/tools/product/layout/layoutPosition04.tsx
  src/customJs/tools/product/layout/layoutPosition05.tsx
Labels: size/S

#1563 Add dynamic and static toggles to different product properties and layouts
  src/App.tsx
  src/customJs/properties/helpers.ts
  src/customJs/properties/product_gallery/ProductGalleryValue.ts
  src/customJs/tools/product/ProductViewer.tsx
  src/customJs/tools/product/index.ts
  src/customJs/tools/product/layout/layoutPosition01.tsx
  src/customJs/tools/product/layout/layoutPosition02.tsx
  src/customJs/tools/product/layout/layoutPosition03.tsx
  src/customJs/tools/product/layout/layoutPosition04.tsx
  src/customJs/tools/product/layout/layoutPosition05.tsx
  src/customJs/tools/product/types.ts
  src/customJs/tools/promo_code/index.test.ts
  src/editorsWebappListenersRegistrator.ts
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/L

#1566 Crear test unitarios sobre producto dinamico
  package-lock.json
  package.json
  src/App.tsx
  src/customJs/tools/product/ProductViewer.test.jsx
  src/customJs/tools/product/index.test.js
  yarn.lock
Labels: size/L

#1569 Resolve local cors issue
  webpack-dev-server.config.js
Labels: size/XS

#1570 Resolve modal issue
  src/customJs/properties/wheel_list/wheelListWidget.tsx
Labels: size/XS

#1572 Fix copy icon
  src/customJs/tools/wheel/wheelFortuneViewer.tsx
Labels: size/XS

#1573 Update roulette translations
  src/customJs/properties/wheel_list/wheelListWidget.tsx
  src/i18n/en.ts
  src/i18n/es.ts
Labels: size/S
